=== test-editor/deprecated-test-editor/xmllib/org.testeditor.xmllibrary/resources/AllActionGroups.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	version="1.0">
<xs:element name="Action" type="Action" >
    <xs:unique name="UniqueAction">
        <xs:selector xpath="Action" />
        <xs:field xpath="@actionName" />
    </xs:unique>
</xs:element>

	<xs:element name="ActionGroups">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ActionGroup" type="ActionGroup"
					maxOccurs="unbounded" />
			</xs:sequence>			
		<xs:attribute name="schemaVersion" type="xs:decimal"  use="required" fixed="1.1"/>		
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ActionGroup">
		<xs:sequence>
			<xs:element name="action" type="Action" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="sort" type="xs:int" use="optional" />
	</xs:complexType>

	<xs:complexType name="Action">
     <xs:sequence>
        <xs:element minOccurs="0"  maxOccurs="1"  ref="actionName" />
         <xs:element minOccurs="0" ref="argument"/>
      </xs:sequence>
      <xs:attribute name="technicalBindingType" use="required" type="xs:string"/>
      <xs:attribute name="sort" type="xs:int" use="optional" />
    </xs:complexType>
  <xs:element name="actionName">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="locator" use="required" type="xs:string"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
    <xs:element name="argument">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="value"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="value" type="xs:string"/>
</xs:schema>

=== test-editor/deprecated-test-editor/core/org.testeditor.demo/demoProjects/DemoWebserviceSoapTests/AllActionGroups.xml
<?xml version="1.0" encoding="UTF-8"?>

<ActionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://testeditor.org/xsd_schema/v_1_1/AllActionGroups.xsd"
	schemaVersion="1.1">

	<ActionGroup name="Time Webservice">
		<action technicalBindingType="Festlegung_Namespace">
			<actionName locator="wsx">WSX</actionName>
            <argument id="argument1">
                <value>http://www.webserviceX.NET/</value>
            </argument>
        </action>
        <action technicalBindingType="Eingabe_Request">
			<actionName locator="wsx:GetSunSetRiseTime/wsx:L/wsx:TimeZone">GetSunSetRiseTime->TimeZone</actionName>
		</action>
        <action technicalBindingType="Eingabe_Request">
			<actionName locator="wsx:GetSunSetRiseTime/wsx:L/wsx:Day">GetSunSetRiseTime->Day</actionName>
		</action>
        <action technicalBindingType="Eingabe_Request">
			<actionName locator="wsx:GetSunSetRiseTime/wsx:L/wsx:Month">GetSunSetRiseTime->Month</actionName>
		</action>
        <action technicalBindingType="Eingabe_Request">
			<actionName locator="wsx:GetSunSetRiseTime/wsx:L/wsx:Year">GetSunSetRiseTime->Year</actionName>
		</action>
        <action technicalBindingType="Aufruf_Webservice">
			<actionName locator="http://www.webservicex.net/sunsetriseservice.asmx">Sunrise</actionName>
		</action>
        <action technicalBindingType="Überprüfung_Response">
			<actionName locator="wsx:GetSunSetRiseTimeResponse/wsx:GetSunSetRiseTimeResult/wsx:SunRiseTime">GetSunSetRiseTimeResponse->SunRiseTime</actionName>
		</action>
	</ActionGroup>

</ActionGroups>

=== test-editor/deprecated-test-editor/fitnesse/org.testeditor.fitnesse.test/testLibrary/AllActionGroups.xml
<?xml version="1.0" encoding="UTF-8"?>
<ActionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../org.testeditor.xmllibrary/resources/AllActionGroups.xsd"
	schemaVersion="1.1">
	<ActionGroup name="Anmeldung">
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Name">Name</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Passwort">Passwort</actionName>
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="LoginButton">LoginButton</actionName>
		</action>
		<action technicalBindingType="Warte_Sekunden" />
	</ActionGroup>
	<ActionGroup name="Willkommen">
		<action technicalBindingType="Pruefe_Wert_vorhanden" />
		<action technicalBindingType="Warte_Sekunden" />
	</ActionGroup>
	<ActionGroup name="Browser">
		<action technicalBindingType="Starte_Browser">
			<actionName locator="Firefox">Firefox</actionName>	
		</action>
		<action technicalBindingType="Navigiere_auf_Seite" />
		<action technicalBindingType="Beende_Browser" />
		<action technicalBindingType="Warte_Sekunden" />
	</ActionGroup>
	<ActionGroup name="Google">
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Sucheingabe">Sucheingabe</actionName>		
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="Suchbutton">Suchbutton</actionName>
		</action>
		<action technicalBindingType="Pruefe_Wert_vorhanden" />
	</ActionGroup>
</ActionGroups>

=== test-editor/deprecated-test-editor/svn/org.testeditor.teamshare.svn.test/testProject/DemoWebTests/AllActionGroups.xml
<?xml version="1.0" encoding="UTF-8"?>

<ActionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../org.testeditor.xmllibrary/resources/AllActionGroups.xsd"
	schemaVersion="1.1">

	<ActionGroup name="Allgemein Browser">
		<action technicalBindingType="Starte_Browser">
			<actionName locator="Firefox">Firefox</actionName>
		</action>
		<action technicalBindingType="Starte_Browser">
			<actionName locator="IE">IE</actionName>
		</action>
		<action technicalBindingType="Navigiere_auf_Seite" />
		<action technicalBindingType="Beende_Browser" />
		<action technicalBindingType="Warte_Sekunden" />
		<action technicalBindingType="Pruefe_Wert_vorhanden" />
		<action technicalBindingType="Pruefe_Wert_nicht_vorhanden" />
	</ActionGroup>

	<ActionGroup name="Lokale Anmeldung">
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="user">Name</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="password">Passwort</actionName>
		</action>
		<action technicalBindingType="Leere_Wert">
			<actionName locator="user">Name</actionName>
		</action>
		<action technicalBindingType="Leere_Wert">
			<actionName locator="password">Passwort</actionName>
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="login">Login</actionName>
		</action>
		<action technicalBindingType="Auswahl_Wert">
       <actionName locator="land"> Land </actionName>
       <argument id="argument1">
              <value>Deutschland</value>
              <value>Italien</value>
              <value>USA</value>
              <value>Schweden</value>
              <value>Australien</value>
       </argument>
       </action>
	</ActionGroup>
	
    
    <ActionGroup name="Google Suche">
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="gbqfq">Sucheingabe</actionName>
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="gbqfba">Suche</actionName>
		</action>
	</ActionGroup>
    
    
    <ActionGroup name="Officewerker Anmeldung">
		<action technicalBindingType="Warte_Element">
			<actionName locator="loginForm">Anmelde-Form</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="loginMandant">Mandant</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="loginName">Benutzer</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="loginPwd">Passwort</actionName>
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="loginButton">Anmelden</actionName>
		</action>
	</ActionGroup>
    
    <ActionGroup name="Officewerker Startseite">
        <action technicalBindingType="Warte_Element">
			<actionName locator="Startseite">Startseite</actionName>
		</action>
        <action technicalBindingType="Button_Druecken">
			<actionName locator="Abmelden">Abmelden</actionName>
		</action>
        <action technicalBindingType="Button_Druecken">
			<actionName locator="Aufwand">Aufwand</actionName>
		</action>
        <action technicalBindingType="Button_Druecken">
			<actionName locator="Eingangsrechnung">Eingangsrechnung</actionName>
		</action>
	</ActionGroup>

    <ActionGroup name="Officewerker Aufwand">
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Art">Art</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Bemerkung">Bemerkung</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Beschreibung">Beschreibung</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Netto">Netto</actionName>
		</action>
        <action technicalBindingType="Button_Druecken">
			<actionName locator="AufwandNeu">AufwandNeu</actionName>
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="Loeschen">Loeschen</actionName>
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="Uebernehmen">Uebernehmen</actionName>
		</action>
	</ActionGroup>

    <ActionGroup name="Officewerker Abfrage">
        <action technicalBindingType="Button_Druecken">
			<actionName locator="JaLoeschen">JaLoeschen</actionName>
		</action>
        <action technicalBindingType="Warte_Element">
			<actionName locator="JaAbmelden">JaAbmelden</actionName>
		</action>
        <action technicalBindingType="Button_Druecken">
			<actionName locator="JaAbmelden">JaAbmelden</actionName>
		</action>
	</ActionGroup>
</ActionGroups>

=== test-editor/deprecated-test-editor/core/org.testeditor.core.test/testLibrary/AllActionGroups.xml
<?xml version="1.0" encoding="UTF-8"?>

<ActionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../org.testeditor.xmllibrary/resources/AllActionGroups.xsd"
		schemaVersion="1.1">

	<ActionGroup name="Allgemein Browser">
		<action technicalBindingType="Starte_Browser">
			<actionName locator="Firefox">Firefox</actionName>
		</action>
		<action technicalBindingType="Starte_Browser">
			<actionName locator="IE">IE</actionName>
		</action>
		<action technicalBindingType="Navigiere_auf_Seite" />
		<action technicalBindingType="Beende_Browser" />
		<action technicalBindingType="Warte_Sekunden" />
		<action technicalBindingType="Pruefe_Wert_vorhanden" />
		<action technicalBindingType="Pruefe_Wert_nicht_vorhanden" />
	</ActionGroup>

	<ActionGroup name="Anmeldung">
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Name">Name</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Passwort">Passwort</actionName>
		</action>
		<action technicalBindingType="Leere_Wert">
			<actionName locator="Name">Name</actionName>
		</action>
		<action technicalBindingType="Leere_Wert">
			<actionName locator="Passwort">Passwort</actionName>
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="Login">Login</actionName>
		</action>
		<action technicalBindingType="Auswahl_Wert">
       		<actionName locator="land"> Land </actionName>
		       <argument id="argument1">
		              <value>Deutschland</value>
		              <value>Italien</value>
		              <value>USA</value>
		              <value>Schweden</value>
		              <value>Australien</value>
		       </argument>
		</action>
		<action technicalBindingType="Auswahl_Wert_andersrum">
       		<actionName locator="land_2"> Land_2 </actionName>
		       <argument id="argument2">
		              <value>Deutschland</value>
		              <value>Italien</value>
		              <value>USA</value>
		              <value>Schweden</value>
		              <value>Australien</value>
		       </argument>
		</action>
		<action technicalBindingType="Auswahl_Wert_andersrum">
       		<actionName locator="WÃ¤hrung"> Waehrung </actionName>
		       <argument id="argument2">
		              <value>USD</value>
		              <value>Euro</value>
		              <value>Rubel</value>
		       </argument>
		</action>
		
	</ActionGroup>
	
</ActionGroups>

=== test-editor/deprecated-test-editor/core/org.testeditor.demo/demoProjects/DemoWebTests/AllActionGroups.xml
<?xml version="1.0" encoding="UTF-8"?>

<ActionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://testeditor.org/xsd_schema/v_1_1/AllActionGroups.xsd"
	schemaVersion="1.1">

	<ActionGroup name="Allgemein Browser">
		<action technicalBindingType="Starte_Browser">
			<actionName locator="Firefox">Firefox</actionName>
		</action>
		<action technicalBindingType="Starte_Browser">
			<actionName locator="IE">IE</actionName>
		</action>
		<action technicalBindingType="Navigiere_auf_Seite" />
		<action technicalBindingType="Beende_Browser" />
		<action technicalBindingType="Warte_Sekunden" />
		<action technicalBindingType="Pruefe_Text_Vorhanden" />
		<action technicalBindingType="Pruefe_Text_Nicht_Vorhanden" />
		<action technicalBindingType="Seitenaufbau_Abwarten" />
	</ActionGroup>

	<ActionGroup name="Lokale Anmeldung">
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="user">Name</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="password">Passwort</actionName>
		</action>
		<action technicalBindingType="Leere_Wert">
			<actionName locator="user">Name</actionName>
		</action>
		<action technicalBindingType="Leere_Wert">
			<actionName locator="password">Passwort</actionName>
		</action>
		<action technicalBindingType="Auswahl_Wert">
			<actionName locator="land"> Land </actionName>
			<argument id="argument1">
				<value>Deutschland</value>
				<value>Italien</value>
				<value>USA</value>
				<value>Schweden</value>
				<value>Australien</value>
			</argument>
		</action>
		<action technicalBindingType="Klicke_Element">
			<actionName locator="login">Login</actionName>
		</action>
		<action technicalBindingType="Pruefe_Text_In_Element">
			<actionName locator="user">Name</actionName>
		</action>
		<action technicalBindingType="Pruefe_Text_In_Element">
			<actionName locator="password">Passwort</actionName>
		</action>
		<action technicalBindingType="Pruefe_Text_In_Element">
			<actionName locator="headline">Ãœberschrift</actionName>
		</action>
	</ActionGroup>

	<ActionGroup name="Google Suche">
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="searchInput">Sucheingabe</actionName>
		</action>
		<action technicalBindingType="Klicke_Element">
			<actionName locator="searchButton">Suche</actionName>
		</action>
	</ActionGroup>

</ActionGroups>

=== test-editor/deprecated-test-editor/core/org.testeditor.demo/demoProjects/DemoWebVaadinTests/AllActionGroups.xml
<?xml version="1.0" encoding="UTF-8"?>

<ActionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://testeditor.org/xsd_schema/v_1_1/AllActionGroups.xsd"
	schemaVersion="1.1">

	<ActionGroup name="Allgemein Browser">
		<action technicalBindingType="Starte_Browser">
			<actionName locator="Firefox">Firefox</actionName>
		</action>
		<action technicalBindingType="Starte_Browser">
			<actionName locator="IE">IE</actionName>
		</action>
		<action technicalBindingType="Navigiere_auf_Seite" />
		<action technicalBindingType="Beende_Browser" />
		<action technicalBindingType="Warte_Sekunden" />
		<action technicalBindingType="Pruefe_Wert_vorhanden" />
		<action technicalBindingType="Pruefe_Wert_nicht_vorhanden" />
	</ActionGroup>
    
    <ActionGroup name="Officewerker Anmeldung">
		<action technicalBindingType="Warte_Element">
			<actionName locator="loginForm">Anmelde-Form</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="loginMandant">Mandant</actionName>
		</action>
				<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Mandant">%Mandant</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="loginName">Benutzer</actionName>
		</action>
		<action technicalBindingType="Leere_Wert">
			<actionName locator="loginName">Benutzer</actionName>
		</action>
		<action technicalBindingType="Leere_Wert">
			<actionName locator="loginMandant">Mandant</actionName>
		</action>
		<action technicalBindingType="Leere_Wert">
			<actionName locator="loginPwd">Passwort</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Name">%Name</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="loginPwd">Passwort</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Pwd">%Passwort</actionName>
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="loginButton">Anmelden</actionName>
		</action>
	</ActionGroup>
    
    <ActionGroup name="Officewerker Startseite">
        <action technicalBindingType="Warte_Element">
			<actionName locator="Startseite">Startseite</actionName>
		</action>
        <action technicalBindingType="Button_Druecken">
			<actionName locator="Abmelden">Abmelden</actionName>
		</action>
        <action technicalBindingType="Button_Druecken">
			<actionName locator="Aufwand">Aufwand</actionName>
		</action>
        <action technicalBindingType="Button_Druecken">
			<actionName locator="Eingangsrechnung">Eingangsrechnung</actionName>
		</action>
	</ActionGroup>

    <ActionGroup name="Officewerker Aufwand">
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Art">Art</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Bemerkung">Bemerkung</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Beschreibung">Beschreibung</actionName>
		</action>
		<action technicalBindingType="Eingabe_Wert">
			<actionName locator="Netto">Netto</actionName>
		</action>
        <action technicalBindingType="Button_Druecken">
			<actionName locator="AufwandNeu">AufwandNeu</actionName>
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="Loeschen">Loeschen</actionName>
		</action>
		<action technicalBindingType="Button_Druecken">
			<actionName locator="Uebernehmen">Uebernehmen</actionName>
		</action>
	</ActionGroup>

    <ActionGroup name="Officewerker Abfrage">
        <action technicalBindingType="Button_Druecken">
			<actionName locator="JaLoeschen">JaLoeschen</actionName>
		</action>
        <action technicalBindingType="Warte_Element">
			<actionName locator="JaAbmelden">JaAbmelden</actionName>
		</action>
        <action technicalBindingType="Button_Druecken">
			<actionName locator="JaAbmelden">JaAbmelden</actionName>
		</action>
	</ActionGroup>
</ActionGroups>

=== test-editor/deprecated-test-editor/core/org.testeditor.demo/demoProjects/DemoEmpty/AllActionGroups.xml
<?xml version="1.0" encoding="UTF-8"?>

<ActionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://testeditor.org/xsd_schema/v_1_1/AllActionGroups.xsd"
	schemaVersion="1.1">

	<ActionGroup name="Allgemein Browser">
		<action technicalBindingType="Starte_Browser">
			<actionName locator="Firefox">Firefox</actionName>
		</action>
		<action technicalBindingType="Starte_Browser">
			<actionName locator="IE">IE</actionName>
		</action>
		<action technicalBindingType="Navigiere_auf_Seite" />
		<action technicalBindingType="Beende_Browser" />
		<action technicalBindingType="Warte_Sekunden" />
		<action technicalBindingType="Pruefe_Text_Vorhanden" />
		<action technicalBindingType="Pruefe_Text_Nicht_Vorhanden" />
		<action technicalBindingType="Seitenaufbau_Abwarten" />
	</ActionGroup>

</ActionGroups>

=== test-editor/deprecated-test-editor/core/org.testeditor.demo/demoProjects/DemoWebserviceRestTests/AllActionGroups.xml
<?xml version="1.0" encoding="UTF-8"?>

<ActionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://testeditor.org/xsd_schema/v_1_1/AllActionGroups.xsd"
	schemaVersion="1.1">
	
    <ActionGroup name="Direction Webservice">
		<action technicalBindingType="Aufruf_Webservice_Get" />
		<action technicalBindingType="Überprüfung_Response">
            <actionName locator="//DirectionsResponse/status/text()">Status</actionName>
        </action>
        <action technicalBindingType="Überprüfung_Response">
            <actionName locator="//DirectionsResponse/route/summary/text()">Summary</actionName>
        </action>
        <action technicalBindingType="Überprüfung_Response">
            <actionName locator="//DirectionsResponse/route/leg/start_address/text()">StartAddress</actionName>
        </action>
	    <action technicalBindingType="Überprüfung_Response">
            <actionName locator="//DirectionsResponse/route/leg/end_address/text()">EndAddress</actionName>
        </action>
        <action technicalBindingType="Überprüfung_Response_Anzahl">
            <actionName locator="//DirectionsResponse/route/leg/step">Step</actionName>
        </action>
	</ActionGroup>
    
	<ActionGroup name="Time Webservice">
		<action technicalBindingType="Aufruf_Webservice_Get" />
		<action technicalBindingType="Überprüfung_Response">
           <actionName locator="//TimeZoneResponse/status/text()">Status</actionName>
        </action>
        <action technicalBindingType="Überprüfung_Response">
            <actionName locator="//TimeZoneResponse/time_zone_id/text()">TimeZoneId</actionName>
        </action>
        <action technicalBindingType="Überprüfung_Response">
            <actionName locator="//TimeZoneResponse/time_zone_name/text()">TimeZoneName</actionName>
        </action>
	</ActionGroup>
	
</ActionGroups>
