=== test-editor/deprecated-test-editor/xmllib/org.testeditor.xmllibrary/resources/TechnicalBindingTypeCollection.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	version="1.0">

	<xs:element name="TechnicalBindingTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TechnicalBindingType" type="TechnicalBindingType"
					maxOccurs="unbounded" />
			</xs:sequence>
				<xs:attribute name="schemaVersion" type="xs:decimal"  use="required" fixed="1.1"/>		
		</xs:complexType>
	</xs:element>

	<xs:complexType name="TechnicalBindingType">
		<xs:sequence>
			<xs:element name="actionPart" type="ActionPart" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="id" type="xs:ID" use="required" />
		<xs:attribute name="sort" type="xs:int" use="optional" />
	</xs:complexType>

	<xs:complexType name="ActionPart">
		<xs:attribute name="position" type="xs:int" use="required" />
		<xs:attribute name="type" type="ActionType" use="required" />
		<xs:attribute name="value" type="xs:string" use="optional" />
		<xs:attribute name="id" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:simpleType name="ActionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TEXT" />
			<xs:enumeration value="ARGUMENT" />
			<xs:enumeration value="ACTION_NAME" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== test-editor/deprecated-test-editor/core/org.testeditor.demo/demoProjects/DemoWebserviceSoapTests/TechnicalBindingTypeCollection.xml
<?xml version="1.0" encoding="UTF-8"?>
<TechnicalBindingTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://testeditor.org/xsd_schema/v_1_1/TechnicalBindingTypeCollection.xsd"
	schemaVersion="1.1">

	<TechnicalBindingType id="Festlegung_Namespace" name="Namespace festlegen">
		<actionPart position="1" type="TEXT" value="setze den Prefix" />
		<actionPart position="2" type="ACTION_NAME"/>
		<actionPart position="3" type="TEXT" value="für den Namespace" />
		<actionPart position="4" type="ARGUMENT" id="argument1"/>
	</TechnicalBindingType>

    <TechnicalBindingType id="Eingabe_Request" name="Request eingeben">
        <actionPart position="1" type="TEXT" value="gebe als Request" />
        <actionPart position="2" type="ACTION_NAME"/>
        <actionPart position="3" type="TEXT" value="den Wert" />
        <actionPart position="4" type="ARGUMENT"/>
        <actionPart position="5" type="TEXT" value="ein" />
    </TechnicalBindingType>

    <TechnicalBindingType id="Aufruf_Webservice" name="Webservice aufrufen">
        <actionPart position="1" type="TEXT" value="rufe den Webservice" />
        <actionPart position="2" type="ACTION_NAME"/>
        <actionPart position="3" type="TEXT" value="auf" />
    </TechnicalBindingType>

    <TechnicalBindingType id="Überprüfung_Response" name="Response überprüfen">
        <actionPart position="1" type="TEXT" value="überprüfe ob der Response" />
        <actionPart position="2" type="ACTION_NAME"/>
        <actionPart position="3" type="TEXT" value="den Wert" />
        <actionPart position="4" type="ARGUMENT"/>
        <actionPart position="5" type="TEXT" value="entspricht" />
    </TechnicalBindingType>

</TechnicalBindingTypes>

=== test-editor/deprecated-test-editor/core/org.testeditor.demo/demoProjects/DemoSwingTests/TechnicalBindingTypeCollection.xml
<?xml version="1.0" encoding="UTF-8"?>
<TechnicalBindingTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://testeditor.org/xsd_schema/v_1_1/TechnicalBindingTypeCollection.xsd"
	schemaVersion="1.1">
	
	<TechnicalBindingType id="Starte_Anwendung" name="Anwendung starten">
		<actionPart position="1" type="TEXT" value="starte Anwendung" />
		<actionPart position="2" type="ARGUMENT" />
	</TechnicalBindingType>

	<TechnicalBindingType id="Beende_Anwendung" name="Anwendung beenden">
		<actionPart position="1" type="TEXT" value="beende Anwendung" />
	</TechnicalBindingType>

	<TechnicalBindingType id="Wert_eingeben" name="Wert eingeben">
		<actionPart position="1" type="TEXT" value="gebe in das Feld" />
		<actionPart position="2" type="ACTION_NAME"/>
		<actionPart position="3" type="TEXT" value="den Wert" />
		<actionPart position="4" type="ARGUMENT"/>
		<actionPart position="5" type="TEXT" value="ein" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Wert_löschen" name="Wert löschen">
		<actionPart position="1" type="TEXT" value="lösche aus dem Feld" />
		<actionPart position="2" type="ACTION_NAME"/>
		<actionPart position="3" type="TEXT" value="den Wert" />
		<actionPart position="4" type="ARGUMENT"/>
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Button_Druecken" name="Button klicken">
		<actionPart position="1" type="TEXT" value="klicke auf" />
		<actionPart position="2" type="ACTION_NAME"/>
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Wert_auswählen" name="Wert auswählen">
		<actionPart position="1" type="TEXT" value="wähle in Feld" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="den Wert" />
		<actionPart position="4" type="ARGUMENT" id="argument1" />
		<actionPart position="5" type="TEXT" value="aus" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="RadioButton_aktivieren" name="RadioButton aktivieren">
		<actionPart position="1" type="TEXT" value="aktiviere Radio-Button" />
		<actionPart position="2" type="ACTION_NAME" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="RadioButton_deaktivieren" name="RadioButton deaktivieren">
		<actionPart position="1" type="TEXT" value="deaktiviere Radio-Button" />
		<actionPart position="2" type="ACTION_NAME" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Checkbox_aktivieren" name="Checkbox aktivieren">
		<actionPart position="1" type="TEXT" value="aktiviere Checkbox" />
		<actionPart position="2" type="ACTION_NAME" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Checkbox_deaktivieren" name="Checkbox deaktivieren">
		<actionPart position="1" type="TEXT" value="deaktiviere Checkbox" />
		<actionPart position="2" type="ACTION_NAME" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Text_ungültig_prüfen" name="Text ungültig prüfen">
		<actionPart position="1" type="TEXT" value="prüfe ob im Feld" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="der Text" />
		<actionPart position="4" type="ARGUMENT" />
		<actionPart position="5" type="TEXT" value="nicht eingetragen ist" />
	</TechnicalBindingType>

	<TechnicalBindingType id="Text_prüfen" name="Text prüfen">
		<actionPart position="1" type="TEXT" value="prüfe ob im Feld" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="der Text" />
		<actionPart position="4" type="ARGUMENT" />
		<actionPart position="5" type="TEXT" value="eingetragen ist" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Wert_ungültig_prüfen" name="Wert ungültig prüfen">
		<actionPart position="1" type="TEXT" value="prüfe ob im Feld" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="der Wert" />
		<actionPart position="4" type="ARGUMENT" />
		<actionPart position="5" type="TEXT" value="nicht ausgewählt ist" />
	</TechnicalBindingType>

	<TechnicalBindingType id="Wert_prüfen" name="Wert prüfen">
		<actionPart position="1" type="TEXT" value="prüfe ob im Feld" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="der Wert" />
		<actionPart position="4" type="ARGUMENT" />
		<actionPart position="5" type="TEXT" value="ausgewählt ist" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Tabellenzeile_auswählen" name="Tabellenzeile auswählen">		
	    <actionPart position="1" type="TEXT" value="in der Tabelle" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="wähle die Zeile" />
		<actionPart position="4" type="ARGUMENT" />
		<actionPart position="5" type="TEXT" value="aus" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Tabellenzeile_doppelklicken" name="Tabellenzeile doppelklicke">		
	    <actionPart position="1" type="TEXT" value="in der Tabelle" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="doppelklicke die Zeile" />
		<actionPart position="4" type="ARGUMENT" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Tabelleneintrag_prüfen" name="Tabelleneintrag prüfen">		
	    <actionPart position="1" type="TEXT" value="prüfe ob in der Tabelle" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="in der letzten Zeile in Spalte" />
		<actionPart position="4" type="ARGUMENT" id="argument1"/>
		<actionPart position="5" type="TEXT" value="der Wert" />
		<actionPart position="6" type="ARGUMENT" />
		<actionPart position="7" type="TEXT" value="eingetragen ist" />
	</TechnicalBindingType>
</TechnicalBindingTypes>

=== test-editor/deprecated-test-editor/svn/org.testeditor.teamshare.svn.test/testProject/DemoWebTests/TechnicalBindingTypeCollection.xml
<?xml version="1.0" encoding="UTF-8"?>
<TechnicalBindingTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../org.testeditor.xmllibrary/resources/TechnicalBindingTypeCollection.xsd"
	schemaVersion="1.1">

	<TechnicalBindingType id="Eingabe_Wert" name="Wert eingeben">
		<actionPart position="1" type="TEXT" value="gebe in das Feld" />
		<actionPart position="2" type="ACTION_NAME"/>
		<actionPart position="3" type="TEXT" value="den Wert" />
		<actionPart position="4" type="ARGUMENT"/>
		<actionPart position="5" type="TEXT" value="ein" />
	</TechnicalBindingType>

	<TechnicalBindingType id="Button_Druecken" name="Button betaetigen">
		<actionPart position="1" type="TEXT" value="klicke auf" />
		<actionPart position="2" type="ACTION_NAME"/>
	</TechnicalBindingType>

	<TechnicalBindingType id="Pruefe_Wert_vorhanden"
		name="Text prüfen">
		<actionPart position="1" type="TEXT" value="überprüfe ob der Text" />
		<actionPart position="2" type="ARGUMENT"/>
		<actionPart position="3" type="TEXT" value="vorhanden ist" />
	</TechnicalBindingType>
	
	<TechnicalBindingType id="Pruefe_Wert_nicht_vorhanden"
		name="Text ungültig prüfen">
		<actionPart position="1" type="TEXT" value="überprüfe ob nicht der Text" />
		<actionPart position="2" type="ARGUMENT"/>
		<actionPart position="3" type="TEXT" value="vorhanden ist" />
	</TechnicalBindingType>

	<TechnicalBindingType id="Starte_Browser" name="Browser starten">
		<actionPart position="1" type="TEXT" value="starte Browser" />
		<actionPart position="2" type="ACTION_NAME"/>
	</TechnicalBindingType>

	<TechnicalBindingType id="Navigiere_auf_Seite"
		name="Seite navigieren">
		<actionPart position="1" type="TEXT" value="navigiere auf die Seite" />
		<actionPart position="2" type="ARGUMENT"/>
	</TechnicalBindingType>

	<TechnicalBindingType id="Beende_Browser" name="Browser beenden">
		<actionPart position="1" type="TEXT" value="beende Browser" />
	</TechnicalBindingType>

	<TechnicalBindingType id="Warte_Sekunden" name="Sekunden warten">
		<actionPart position="1" type="TEXT" value="warte" />
		<actionPart position="2" type="ARGUMENT"/>
		<actionPart position="3" type="TEXT" value="Sekunden" />
	</TechnicalBindingType>

	<TechnicalBindingType id="Warte_Element" name="auf Element warten">
		<actionPart position="1" type="TEXT" value="warte auf Element" />
		<actionPart position="2" type="ACTION_NAME"/>
	</TechnicalBindingType>

	<TechnicalBindingType id="Leere_Wert" name="Wert leeren">
		<actionPart position="1" type="TEXT" value="leere das Feld" />
		<actionPart position="2" type="ACTION_NAME"/>
	</TechnicalBindingType>

	<TechnicalBindingType id="Auswahl_Wert" name="Wert auswählen">
		<actionPart position="1" type="TEXT" value="wähle in Feld" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="den Wert" />
		<actionPart position="4" type="ARGUMENT" id="argument1" />
		<actionPart position="5" type="TEXT" value="aus" />
	</TechnicalBindingType>
</TechnicalBindingTypes>

=== test-editor/deprecated-test-editor/core/org.testeditor.demo/demoProjects/DemoWebserviceRestTests/TechnicalBindingTypeCollection.xml
<?xml version="1.0" encoding="UTF-8"?>
<TechnicalBindingTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://testeditor.org/xsd_schema/v_1_1/TechnicalBindingTypeCollection.xsd"
	schemaVersion="1.1">

    <TechnicalBindingType id="Aufruf_Webservice_Get" name="Webservice aufrufen">
        <actionPart position="1" type="TEXT" value="rufe den Webservice" />
        <actionPart position="2" type="ARGUMENT"/>
        <actionPart position="3" type="TEXT" value="auf" />
    </TechnicalBindingType>

	<TechnicalBindingType id="Überprüfung_Response_Anzahl" name="Response zählen">
		<actionPart position="1" type="TEXT" value="überprüfe ob der Response" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="insgesamt" />
		<actionPart position="4" type="ARGUMENT"/>
		<actionPart position="5" type="TEXT" value="Mal vorhanden ist" />
    </TechnicalBindingType>
    
    <TechnicalBindingType id="Überprüfung_Response" name="Response überprüfen">
		<actionPart position="1" type="TEXT" value="überprüfe ob der Response" />
		<actionPart position="2" type="ACTION_NAME" />
		<actionPart position="3" type="TEXT" value="dem Wert" />
		<actionPart position="4" type="ARGUMENT" />
		<actionPart position="5" type="TEXT" value="entspricht" />
	</TechnicalBindingType>
		
</TechnicalBindingTypes>
